### ISSUE TITLE
Unable to follow README instructions on Windows

### ISSUE THREAD

**Issue by clin1234** [revng/orchestra#152]
Running python setup.py bdist_wheel yielded the following:

Traceback (most recent call last):
  File "C:\Users\ךינשגכהד\src\revng-orchestra\setup.py", line 84, in <module>
    subprocess.check_call([ensure_ytt_path])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\subprocess.py", line 414, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\subprocess.py", line 395, in call
    with Popen(*popenargs, **kwargs) as p:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by aleclearmind** [comment]
Windows is not supported, as of now. Please use WSL.
