### ISSUE TITLE
orc fails with strange error - "'NoneType' object has no attribute 'encode'"

### ISSUE THREAD

**Issue by edrdo** [revng/orchestra#18]
Hi, 

I installed orchestra as mentioned in the README.md file:

```
pip3 install --user --force-reinstall https://github.com/revng/revng-orchestra/archive/master.zip
```
... but I am getting a strange error with orchestra commands, e.g. (with Python 3.7 on Debian 10):

```
$ git clone https://github.com/revng/orchestra
$ cd orchestra
$ orc components
[+] INFO - This is the first time you run orchestra, welcome!
[+] INFO - Creating default user options in .orchestra/config/user_options.yml
[+] INFO - Populating default remotes for repositories and binary archives
[+] INFO - Remember to run `orc update` next
[+] INFO - Checking for redirects in https://github.com/revng/binary-archives
[+] INFO - Redirecting to https://rev.ng/gitlab/revng/binary-archives.git
Traceback (most recent call last):
  File "/home/edrdo/.local/bin/orc", line 10, in <module>
    sys.exit(main())
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/__init__.py", line 28, in main
    return cmd_parser.handler(args)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/cmds/components.py", line 35, in handle_components
    config = Configuration(use_config_cache=args.config_cache)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 110, in __init__
    self._parse_components()
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 247, in _parse_components
    set_self_hash(component, component_yaml)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 434, in set_self_hash
    to_hash += component.commit().encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

Another example:

```
$ orc environment
Traceback (most recent call last):
  File "/home/edrdo/.local/bin/orc", line 10, in <module>
    sys.exit(main())
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/__init__.py", line 28, in main
    return cmd_parser.handler(args)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/cmds/environment.py", line 13, in handle_environment
    config = Configuration(use_config_cache=args.config_cache)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 110, in __init__
    self._parse_components()
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 247, in _parse_components
    set_self_hash(component, component_yaml)
  File "/home/edrdo/.local/lib/python3.7/site-packages/orchestra/model/configuration.py", line 434, in set_self_hash
    to_hash += component.commit().encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

Any idea why this happens and how it can be fixed? 

Thanks

**Comment by mrexodia** [comment]
If you run with `--loglevel DEBUG` you will see that it tries to fetch from https://github.com/revng/caliban (which is private at the moment).

**Comment by fcremo** [comment]
Thanks for reporting this, we are testing a fix and we will merge it soon

**Comment by aleclearmind** [comment]
The fix has been merged, can you please test and retry?
Thanks.

**Comment by edrdo** [comment]
Thanks, it works now.
